// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BrowserResult(arg1, arg2) {
  return window['go']['main']['App']['BrowserResult'](arg1, arg2);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function CollectSystemInfo() {
  return window['go']['main']['App']['CollectSystemInfo']();
}

export function GetAPIKeyStatus() {
  return window['go']['main']['App']['GetAPIKeyStatus']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function LoadHistory() {
  return window['go']['main']['App']['LoadHistory']();
}

export function SendMessage(arg1) {
  return window['go']['main']['App']['SendMessage'](arg1);
}

export function SetAPIKey(arg1) {
  return window['go']['main']['App']['SetAPIKey'](arg1);
}

export function Stop() {
  return window['go']['main']['App']['Stop']();
}
