// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearHistory():Promise<void>;

export function CollectSystemInfo():Promise<string>;

export function GetAPIKeyStatus():Promise<boolean>;

export function LoadHistory():Promise<Array<main.ChatMsg>>;

export function SendMessage(arg1:string):Promise<string>;

export function SetAPIKey(arg1:string):Promise<void>;

export function Stop():Promise<void>;
